"use client";
import { useState } from "react";
import { ArrowDown, ArrowUp, CalendarDays, ChevronLeft, ChevronRight, FileText, Pencil, Plus, Trash2, Users, LockKeyhole, GripVertical } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel } from "@/components/ui/alert-dialog";
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from "@/components/ui/empty";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Progress } from "@/components/ui/progress";
import { roles, statuses, priorities, platforms, managers, strategists, canMove, editableFields, canDelete, type Actor, type ContentItem, type Pillar, type WorkspaceData, type Member, type Collection } from "@/lib/hub-types";
import { api, dateLabel, initials } from "./creative-hub";
type Reload = () => Promise<WorkspaceData>;

export function Choice({ id, label, value, options, onChange, disabled }: { id?: string; label: string; value: string; options: { value: string; label: string }[]; onChange: (value: string) => void; disabled?: boolean }) {
  return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger id={id} aria-label={label} className="w-full"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(x => <SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>;
}
export const options = (list: readonly string[]) => list.map(x => ({ value: x, label: x }));
export function Field({ label, id, children, wide }: { label: string; id: string; children: React.ReactNode; wide?: boolean }) {
  return <div className={wide ? "form-field field-wide" : "form-field"}><Label htmlFor={id}>{label}</Label>{children}</div>;
}
export function EmptyState({ title, description }: { title: string; description: string }) { return <Empty className="hub-empty"><FileText size={24}/><EmptyHeader><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader></Empty>; }
export function StatusBadge({ status }: { status: ContentItem["status"] }) { return <span className={"status-badge status-" + status.toLowerCase()}><i/>{status}</span>; }
export function PriorityBadge({ priority }: { priority: ContentItem["priority"] }) { return <span className={"priority priority-" + priority.toLowerCase()}>{priority === "Urgent" ? "!! " : priority === "High" ? "↑ " : ""}{priority}</span>; }
export function Confirm({ open, close, title, description, label, action }: { open: boolean; close: () => void; title: string; description: string; label: string; action: () => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  return <AlertDialog open={open} onOpenChange={value => { if (!value && !busy) { setError(""); close(); } }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription></AlertDialogHeader>{error && <p role="alert" className="form-error">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><Button variant="destructive" disabled={busy} onClick={async () => { setBusy(true); setError(""); try { await action(); close(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>{busy ? "Working…" : label}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>;
}
export function ContentEditor({ item, data, close, save, move }: { item: ContentItem | null; data: WorkspaceData; close: () => void; save: (payload: Record<string, unknown>) => Promise<void>; move: (item: ContentItem, status: ContentItem["status"], decision?: string) => Promise<void> }) {
  const fields = editableFields(data.actor, item);
  const [form, setForm] = useState({ title: item?.title ?? "", publishDate: item?.publishDate ?? new Date().toLocaleDateString("en-CA"), pillarId: item?.pillarId ?? null, brand: item?.brand ?? data.collections.find(x => x.kind === "brand")?.name ?? "Creative Hub", campaign: item?.campaign ?? "", platform: item?.platform ?? "Instagram", pic: item?.pic ?? (data.actor.role === "Creative" ? data.actor.name : ""), assigneeId: item?.assigneeId ?? (data.actor.role === "Creative" ? data.actor.id : null), priority: item?.priority ?? "Normal", status: item?.status ?? "Idea", caption: item?.caption ?? "", notes: item?.notes ?? "" });
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [reject, setReject] = useState(false);
  function update(key: string, value: unknown) { setForm(current => ({ ...current, [key]: value })); }
  const enabled = (key: string) => fields.includes(key);
  const moves = item ? statuses.filter(x => x === item.status || canMove(data.actor, item, x)) : managers(data.actor.role) ? statuses : ["Idea"];
  const canSave = fields.length > 0 || !!item && moves.length > 1;
  const allowedPillars = data.pillars.filter(x => x.active || x.id === item?.pillarId);
  const readonly = !canSave;
  async function submit(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setError("");
    try {
      const payload: Record<string, unknown> = item ? { version: item.version } : { ...form };
      if (item) for (const [key, value] of Object.entries(form)) { if (fields.includes(key) || key === "status" && moves.length > 1) payload[key] = value; }
      await save(payload);
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <Dialog open onOpenChange={value => !value && !busy && close()}><DialogContent className="content-modal"><form onSubmit={submit}><DialogHeader><DialogTitle>{item ? readonly ? "Content details" : "Edit content" : "New content"}</DialogTitle><DialogDescription>{readonly ? "You have read-only access to this item." : "Changes are saved to your workspace."}</DialogDescription></DialogHeader>
    <div className="modal-scroll"><div className="form-grid">
      <Field label="Content title" id="content-title" wide><Input id="content-title" maxLength={200} required disabled={!enabled("title")} value={form.title} onChange={e => update("title", e.target.value)}/></Field>
      <Field label="Brand" id="content-brand"><Choice id="content-brand" label="Brand" value={form.brand} options={options(data.collections.filter(x => x.kind === "brand").map(x => x.name))} disabled={!enabled("brand")} onChange={v => update("brand", v)}/></Field>
      <Field label="Campaign" id="content-campaign"><Choice id="content-campaign" label="Campaign" value={form.campaign || "_none"} options={[{ value: "_none", label: "No campaign" }, ...options(data.collections.filter(x => x.kind === "campaign").map(x => x.name))]} disabled={!enabled("campaign")} onChange={v => update("campaign", v === "_none" ? "" : v)}/></Field>
      <Field label="Content pillar" id="content-pillar"><Choice id="content-pillar" label="Content pillar" value={form.pillarId == null ? "_none" : String(form.pillarId)} options={[{ value: "_none", label: "No pillar" }, ...allowedPillars.map(x => ({ value: String(x.id), label: x.name + (x.active ? "" : " · inactive") }))]} disabled={!enabled("pillarId")} onChange={v => update("pillarId", v === "_none" ? null : Number(v))}/></Field>
      <Field label="Platform" id="content-platform"><Choice id="content-platform" label="Platform" value={form.platform} options={options([...new Set([...platforms, form.platform])])} disabled={!enabled("platform")} onChange={v => update("platform", v)}/></Field>
      <Field label="Publish date" id="content-date"><Input id="content-date" type="date" required disabled={!enabled("publishDate")} value={form.publishDate} onChange={e => update("publishDate", e.target.value)}/></Field>
      <Field label="Priority" id="content-priority"><Choice id="content-priority" label="Priority" value={form.priority} options={options(priorities)} disabled={!enabled("priority")} onChange={v => update("priority", v)}/></Field>
      <Field label="Assigned team member" id="content-assignee"><Choice id="content-assignee" label="Assigned team member" value={form.assigneeId == null ? "_none" : String(form.assigneeId)} options={[{ value: "_none", label: "Unassigned / existing PIC" }, ...data.members.filter(x => x.status !== "Inactive" || x.id === item?.assigneeId).map(x => ({ value: String(x.id), label: x.name }))]} disabled={!enabled("assigneeId")} onChange={v => { update("assigneeId", v === "_none" ? null : Number(v)); if (v !== "_none") update("pic", data.members.find(x => x.id === Number(v))?.name ?? ""); }}/></Field>
      <Field label="Workflow status" id="content-status"><Choice id="content-status" label="Workflow status" value={form.status} options={options(moves)} disabled={moves.length < 2} onChange={v => update("status", v)}/></Field>
      {form.assigneeId == null && <Field label="PIC / person in charge" id="content-pic" wide><Input id="content-pic" maxLength={120} disabled={!enabled("pic")} value={form.pic} onChange={e => update("pic", e.target.value)} placeholder="Keep an existing PIC name, or select a team member above"/><small>Assign a team member above to grant Creative or Designer access.</small></Field>}
      <Field label="Caption" id="content-caption" wide><Textarea id="content-caption" maxLength={15000} rows={4} disabled={!enabled("caption")} value={form.caption} onChange={e => update("caption", e.target.value)}/></Field>
      <Field label="Notes" id="content-notes" wide><Textarea id="content-notes" maxLength={15000} rows={3} disabled={!enabled("notes")} value={form.notes} onChange={e => update("notes", e.target.value)}/></Field>
    </div>{item?.reviewDecision === "rejected" && <p className="form-error">Rejected — this content has been returned for revision.</p>}{error && <p className="form-error" role="alert">{error}</p>}
      {item?.status === "Review" && ["Owner", "Admin", "Approver"].includes(data.actor.role) && <div className="review-actions"><Button type="button" variant="outline" onClick={() => void move(item, "Approved")} disabled={busy}>Approve</Button><Button type="button" variant="outline" onClick={() => void move(item, "Revision")} disabled={busy}>Request revision</Button><Button type="button" variant="destructive" onClick={() => setReject(true)} disabled={busy}>Reject</Button></div>}
    </div><DialogFooter><Button type="button" variant="outline" disabled={busy} onClick={close}>{readonly ? "Close" : "Cancel"}</Button>{canSave && <Button type="submit" disabled={busy}>{busy ? "Saving…" : "Save content"}</Button>}</DialogFooter></form>
    <Confirm open={reject} close={() => setReject(false)} title="Reject this content?" description="The item will move to Revision and be marked as rejected. It will not be deleted." label="Reject content" action={() => move(item!, "Revision", "rejected")}/>
  </DialogContent></Dialog>;
}
export function ContentTable({ items, actor, open, remove, compact = false }: { items: ContentItem[]; actor: Actor; open: (item: ContentItem) => void; remove?: (item: ContentItem) => void; compact?: boolean }) {
  const [limit, setLimit] = useState(40);
  if (!items.length) return <EmptyState title="No content to show" description="Try another filter, or add a new content item."/>;
  return <div className={compact ? "" : "panel"}><Table><TableHeader><TableRow><TableHead>Content title</TableHead><TableHead>Publish date</TableHead><TableHead>PIC</TableHead><TableHead>Status</TableHead>{!compact && <><TableHead>Priority</TableHead><TableHead><span className="sr-only">Actions</span></TableHead></>}</TableRow></TableHeader><TableBody>{items.slice(0, limit).map(item => <TableRow key={item.id}><TableCell className="title-cell"><button onClick={() => open(item)}>{item.title}</button><span>{item.brand} · {item.platform}{item.pillar ? " · " + item.pillar : ""}</span></TableCell><TableCell className="nowrap">{dateLabel(item.publishDate)}</TableCell><TableCell>{item.pic || "Unassigned"}</TableCell><TableCell><StatusBadge status={item.status}/></TableCell>{!compact && <><TableCell><PriorityBadge priority={item.priority}/></TableCell><TableCell><div className="table-actions"><Button size="icon" variant="ghost" aria-label={"Open " + item.title} onClick={() => open(item)}><Pencil size={15}/></Button>{canDelete(actor.role) && remove && <Button size="icon" variant="ghost" aria-label={"Delete " + item.title} onClick={() => remove(item)}><Trash2 size={15}/></Button>}</div></TableCell></>}</TableRow>)}</TableBody></Table>{items.length > limit && <div className="load-more"><Button variant="outline" onClick={() => setLimit(limit + 40)}>Show 40 more · {items.length - limit} remaining</Button></div>}</div>;
}

export function PillarsView({ data, reload }: { data: WorkspaceData; reload: Reload }) {
  const [edit, setEdit] = useState<Pillar | "new" | null>(null); const [remove, setRemove] = useState<Pillar | null>(null); const [busy, setBusy] = useState(false);
  const allowed = strategists(data.actor.role);
  async function reorder(index: number, offset: number) {
    const ids = data.pillars.map(x => x.id); [ids[index], ids[index + offset]] = [ids[index + offset], ids[index]];
    setBusy(true); try { await api("pillars/reorder", "PATCH", { ids }); await reload(); toast.success("Pillar order saved"); } catch (e) { toast.error((e as Error).message); } finally { setBusy(false); }
  }
  return <><div className="section-toolbar"><span>{data.pillars.length} pillars · {data.pillars.filter(x => x.active).length} active</span>{allowed && <Button onClick={() => setEdit("new")}><Plus size={16}/>Add pillar</Button>}</div><div className="pillar-grid">{data.pillars.map((pillar, index) => <article className={"panel pillar-card" + (pillar.active ? "" : " inactive-pillar")} key={pillar.id}><div className="pillar-card-top"><span className="pillar-swatch" style={{ background: pillar.color }}/><span className={"subtle-badge" + (pillar.active ? "" : " muted")}>{pillar.active ? "Active" : "Inactive"}</span>{allowed && <div className="pillar-order"><Button size="icon" variant="ghost" aria-label={"Move " + pillar.name + " up"} disabled={busy || !index} onClick={() => void reorder(index, -1)}><ArrowUp size={15}/></Button><Button size="icon" variant="ghost" aria-label={"Move " + pillar.name + " down"} disabled={busy || index === data.pillars.length - 1} onClick={() => void reorder(index, 1)}><ArrowDown size={15}/></Button></div>}</div><h2>{pillar.name}</h2><p>{pillar.description || "No description yet."}</p><div className="pillar-objective"><span>OBJECTIVE</span><p>{pillar.objective || "Not set"}</p></div><footer><span>{pillar.usage} content {pillar.usage === 1 ? "item" : "items"}</span>{allowed && <div className="table-actions"><Button size="sm" variant="ghost" onClick={() => setEdit(pillar)}>Edit</Button><Button size="icon" variant="ghost" aria-label={"Delete pillar " + pillar.name} onClick={() => setRemove(pillar)}><Trash2 size={15}/></Button></div>}</footer></article>)}</div>{!data.pillars.length && <EmptyState title="Define your first content pillar" description="Pillars help organize the topics your brand talks about."/>}
    {edit && <PillarEditor pillar={edit === "new" ? null : edit} close={() => setEdit(null)} saved={reload}/>}
    <Confirm open={!!remove} close={() => setRemove(null)} title="Delete this pillar?" description={(remove?.usage ?? 0) + " content items use “" + (remove?.name ?? "") + "”. They will be kept, but will no longer have a pillar assigned. You can also make this pillar inactive instead."} label="Delete pillar" action={async () => { await api("pillars/" + remove!.id, "DELETE", { confirm: true }); await reload(); toast.success("Pillar deleted. Content preserved."); }}/>
  </>;
}
function PillarEditor({ pillar, close, saved }: { pillar: Pillar | null; close: () => void; saved: Reload }) {
  const [form, setForm] = useState({ name: pillar?.name ?? "", description: pillar?.description ?? "", objective: pillar?.objective ?? "", color: pillar?.color ?? "#2563eb", active: pillar ? !!pillar.active : true });
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  return <Dialog open onOpenChange={v => !v && !busy && close()}><DialogContent className="standard-modal"><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); try { await api("pillars" + (pillar ? "/" + pillar.id : ""), pillar ? "PUT" : "POST", form); await saved(); close(); toast.success("Pillar saved"); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><DialogHeader><DialogTitle>{pillar ? "Edit content pillar" : "New content pillar"}</DialogTitle><DialogDescription>Inactive pillars remain on existing content and cannot be assigned to new content.</DialogDescription></DialogHeader><div className="modal-scroll form-grid"><Field id="pillar-name" label="Name" wide><Input id="pillar-name" required maxLength={100} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></Field><Field id="pillar-description" label="Description" wide><Textarea id="pillar-description" maxLength={2000} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></Field><Field id="pillar-objective" label="Objective" wide><Textarea id="pillar-objective" maxLength={1000} value={form.objective} onChange={e => setForm({ ...form, objective: e.target.value })}/></Field><Field id="pillar-color" label="Color"><div className="color-picker"><Input id="pillar-color" type="color" value={form.color} onChange={e => setForm({ ...form, color: e.target.value })}/><span>{form.color}</span></div></Field><Field id="pillar-active" label="Active"><Switch id="pillar-active" checked={form.active} onCheckedChange={active => setForm({ ...form, active })}/></Field>{error && <p role="alert" className="form-error field-wide">{error}</p>}</div><DialogFooter><Button type="button" variant="outline" disabled={busy} onClick={close}>Cancel</Button><Button disabled={busy}>{busy ? "Saving…" : "Save pillar"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function CollectionsView({ data, kind, reload }: { data: WorkspaceData; kind: "brand" | "campaign"; reload: Reload }) {
  const [edit, setEdit] = useState<Collection | "new" | null>(null);
  const allowed = kind === "brand" ? managers(data.actor.role) : strategists(data.actor.role);
  const list = data.collections.filter(x => x.kind === kind);
  return <><div className="section-toolbar"><span>{list.length} {kind === "brand" ? "brands" : "campaigns"}</span>{allowed && <Button onClick={() => setEdit("new")}><Plus size={16}/>Add {kind}</Button>}</div><div className="collection-grid">{list.map(x => { const items = data.items.filter(item => item[kind] === x.name); const ready = items.filter(i => ["Approved", "Scheduled"].includes(i.status)).length; return <article className="panel collection-card" key={x.id}><div className="collection-top"><span className="collection-monogram">{initials(x.name)}</span>{allowed && <Button size="sm" variant="ghost" onClick={() => setEdit(x)}>Edit</Button>}</div><h2>{x.name}</h2><p>{x.description || "No description yet."}</p><div className="collection-count"><span>{items.length} content items</span><strong>{ready} ready</strong></div><Progress value={items.length ? ready / items.length * 100 : 0}/></article>; })}</div>{edit && <CollectionEditor kind={kind} item={edit === "new" ? null : edit} close={() => setEdit(null)} reload={reload}/>}</>;
}
function CollectionEditor({ kind, item, close, reload }: { kind: "brand" | "campaign"; item: Collection | null; close: () => void; reload: Reload }) {
  const [name, setName] = useState(item?.name ?? ""); const [description, setDescription] = useState(item?.description ?? ""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  return <Dialog open onOpenChange={v => !v && !busy && close()}><DialogContent className="standard-modal"><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { await api("collections" + (item ? "/" + item.id : ""), item ? "PUT" : "POST", { kind, name, description }); await reload(); close(); toast.success("Saved"); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><DialogHeader><DialogTitle>{item ? "Edit " : "New "}{kind}</DialogTitle><DialogDescription>{kind === "brand" ? "Give your content a consistent identity." : "Group related content under one initiative."}</DialogDescription></DialogHeader><div className="modal-scroll form-grid"><Field label="Name" id="collection-name" wide><Input id="collection-name" required maxLength={100} value={name} onChange={e => setName(e.target.value)}/></Field><Field label="Description" id="collection-description" wide><Textarea id="collection-description" maxLength={2000} value={description} onChange={e => setDescription(e.target.value)}/></Field>{error && <p role="alert" className="form-error">{error}</p>}</div><DialogFooter><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button disabled={busy}>{busy ? "Saving…" : "Save"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function CalendarView({ items, open }: { items: ContentItem[]; open: (item: ContentItem) => void }) {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [selected, setSelected] = useState<string | null>(null);
  const year = month.getFullYear(), m = month.getMonth(), days = new Date(year, m + 1, 0).getDate();
  const count = Math.ceil((month.getDay() + days) / 7) * 7;
  const dayString = (day: number) => year + "-" + String(m + 1).padStart(2, "0") + "-" + String(day).padStart(2, "0");
  const monthItems = items.filter(x => x.publishDate.startsWith(dayString(1).slice(0, 7)));
  const showItems = selected ? items.filter(x => x.publishDate === selected) : monthItems;
  return <><div className="section-toolbar calendar-toolbar"><h2>{month.toLocaleDateString("en-US", { month: "long", year: "numeric" })}</h2><div className="table-actions"><Button variant="outline" size="icon" aria-label="Previous month" onClick={() => { setMonth(new Date(year, m - 1, 1)); setSelected(null); }}><ChevronLeft size={17}/></Button><Button variant="outline" onClick={() => { setMonth(new Date(new Date().getFullYear(), new Date().getMonth(), 1)); setSelected(null); }}>Today</Button><Button variant="outline" size="icon" aria-label="Next month" onClick={() => { setMonth(new Date(year, m + 1, 1)); setSelected(null); }}><ChevronRight size={17}/></Button></div></div><div className="panel calendar-panel"><div className="calendar-weekdays">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map(x => <div key={x}>{x}</div>)}</div><div className="calendar-grid">{Array.from({ length: count }, (_, i) => { const day = i - month.getDay() + 1; const valid = day > 0 && day <= days; const date = valid ? dayString(day) : ""; const list = items.filter(x => x.publishDate === date); return <div className={"calendar-day" + (!valid ? " outside-month" : "") + (date === new Date().toLocaleDateString("en-CA") ? " today" : "")} key={i}>{valid && <><button className="day-number" aria-label={"Show content for " + date} onClick={() => setSelected(selected === date ? null : date)}>{day}</button><div className="calendar-posts">{list.slice(0, 3).map(x => <button key={x.id} className={"calendar-post status-" + x.status.toLowerCase()} onClick={() => open(x)} title={x.title}>{x.title}</button>)}{list.length > 3 && <button className="calendar-more" onClick={() => setSelected(date)}>+{list.length - 3} more</button>}</div>{!!list.length && <span className="mobile-day-count">{list.length}</span>}</>}</div>; })}</div></div><section className={"calendar-agenda panel" + (selected ? " agenda-selected" : "")}><div className="panel-heading"><h2>{selected ? dateLabel(selected) : "This month"} · {showItems.length} items</h2>{selected && <Button variant="ghost" onClick={() => setSelected(null)}>Show month</Button>}</div>{!showItems.length ? <EmptyState title="Nothing scheduled" description="Content with a publish date in this period appears here."/> : showItems.map(x => <button className="agenda-row" key={x.id} onClick={() => open(x)}><span>{dateLabel(x.publishDate)}</span><strong>{x.title}</strong><StatusBadge status={x.status}/></button>)}</section></>;
}

export function TeamView({ data, reload }: { data: WorkspaceData; reload: Reload }) {
  const [add, setAdd] = useState(false);
  if (!managers(data.actor.role)) return <EmptyState title="Team settings are restricted" description="Only the Owner and Admin can manage team members."/>;
  return <><div className="section-toolbar"><span>{data.members.length} workspace members</span><Button onClick={() => setAdd(true)}><Plus size={16}/>Add member</Button></div><div className="access-note"><LockKeyhole size={18}/><p>Adding a member saves their role here. This site is private: the owner must also grant that email access through the site's sharing settings. No invitation email is sent by this form.</p></div><section className="panel"><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Email</TableHead><TableHead>Role</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{data.members.map(member => <MemberRow key={member.id + member.role + member.status} member={member} self={member.id === data.actor.id} reload={reload}/>)}</TableBody></Table></section>{add && <MemberEditor close={() => setAdd(false)} reload={reload}/>}</>;
}
function MemberRow({ member, self, reload }: { member: Member; self: boolean; reload: Reload }) {
  const [role, setRole] = useState(member.role); const [busy, setBusy] = useState(false); const [disable, setDisable] = useState(false);
  const protectedMember = member.role === "Owner" || self;
  async function update(values: Record<string, unknown>) { setBusy(true); try { await api("members/" + member.id, "PATCH", values); await reload(); toast.success("Member updated"); } finally { setBusy(false); } }
  return <TableRow><TableCell><div className="member-name"><span className="avatar">{initials(member.name)}</span><strong>{member.name}{self ? " (you)" : ""}</strong></div></TableCell><TableCell>{member.email}</TableCell><TableCell>{protectedMember ? <span className="owner-role">{member.role}<LockKeyhole size={13}/></span> : <Choice label={"Role for " + member.name} value={role} options={options(roles.filter(x => x !== "Owner"))} disabled={busy} onChange={v => setRole(v as Member["role"])}/>}</TableCell><TableCell><span className="subtle-badge">{member.status}</span></TableCell><TableCell>{!protectedMember && <div className="table-actions"><Button size="sm" variant="outline" disabled={busy || role === member.role} onClick={() => void update({ role }).catch(e => toast.error(e.message))}>Save role</Button><Button size="sm" variant="ghost" disabled={busy} onClick={() => member.status === "Inactive" ? void update({ status: member.userId ? "Active" : "Invited" }).catch(e => toast.error(e.message)) : setDisable(true)}>{member.status === "Inactive" ? "Reactivate" : "Disable"}</Button></div>}<Confirm open={disable} close={() => setDisable(false)} title={"Disable " + member.name + "?"} description="This member will lose workspace access. Their assigned content will be preserved." label="Disable member" action={() => update({ status: "Inactive" })}/></TableCell></TableRow>;
}
function MemberEditor({ close, reload }: { close: () => void; reload: Reload }) {
  const [form, setForm] = useState({ name: "", email: "", role: "Viewer" }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  return <Dialog open onOpenChange={v => !v && !busy && close()}><DialogContent className="standard-modal"><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { await api("members", "POST", form); await reload(); close(); toast.success("Member added"); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><DialogHeader><DialogTitle>Add a team member</DialogTitle><DialogDescription>Use the email address they use to sign in with ChatGPT.</DialogDescription></DialogHeader><div className="modal-scroll form-grid"><Field id="member-name" label="Name" wide><Input id="member-name" required maxLength={120} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></Field><Field id="member-email" label="Email" wide><Input id="member-email" required type="email" maxLength={254} value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/></Field><Field id="member-role" label="Role" wide><Choice id="member-role" label="Role" value={form.role} options={options(roles.filter(x => x !== "Owner"))} onChange={role => setForm({ ...form, role })}/></Field>{error && <p className="form-error" role="alert">{error}</p>}</div><DialogFooter><Button type="button" variant="outline" disabled={busy} onClick={close}>Cancel</Button><Button disabled={busy}>{busy ? "Adding…" : "Add member"}</Button></DialogFooter></form></DialogContent></Dialog>;
}
export function WorkspaceSettings({ data, reload }: { data: WorkspaceData; reload: Reload }) {
  const [name, setName] = useState(data.workspace.name); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  if (data.actor.role !== "Owner") return <EmptyState title="Workspace settings are restricted" description="Only the Owner can change these settings."/>;
  return <section className="panel settings-panel"><h2>Workspace details</h2><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { await api("workspace", "PATCH", { name }); await reload(); toast.success("Workspace saved"); setError(""); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><Field label="Workspace name" id="workspace-name"><Input id="workspace-name" maxLength={100} required value={name} onChange={e => setName(e.target.value)}/></Field><p>The Owner role is protected. It cannot be removed or reassigned here.</p>{error && <p className="form-error" role="alert">{error}</p>}<Button disabled={busy}>{busy ? "Saving…" : "Save workspace"}</Button></form></section>;
}
